"""/api/alerts — Signals & Alerts: threshold rules, evaluation, history, digest."""
import datetime as dt

from fastapi import APIRouter, HTTPException
from fastapi.responses import HTMLResponse
from pydantic import BaseModel

from backend import config
from backend.services import alerts, news_aggregator

router = APIRouter(prefix="/api/alerts", tags=["alerts"])


class RuleRequest(BaseModel):
    index: str
    metric: str
    operator: str
    threshold: float


@router.get("/rules")
def rules():
    return {"rules": alerts.list_rules(), "metrics": alerts.METRICS,
            "indices": [{"id": i, "name": config.INDICES[i]["name"]} for i in config.INDEX_ORDER]}


@router.post("/rules")
def create_rule(req: RuleRequest):
    try:
        return alerts.add_rule(req.index, req.metric, req.operator, req.threshold)
    except ValueError as exc:
        raise HTTPException(400, str(exc))


@router.delete("/rules/{rule_id}")
def remove_rule(rule_id: str):
    if not alerts.delete_rule(rule_id):
        raise HTTPException(404, "rule not found")
    return {"deleted": True}


@router.post("/evaluate")
def evaluate():
    """Evaluate all rules against fresh data; returns newly fired alerts."""
    return {"fired": alerts.evaluate(), "history": alerts.get_history(20)}


@router.get("/history")
def history():
    return {"history": alerts.get_history()}


@router.get("/digest", response_class=HTMLResponse)
def weekly_digest():
    """Standalone HTML digest (model summary + top news) for team meetings."""
    from backend.data.dummy import generate as model_store
    model = model_store.ensure()
    s = model["summary"]
    try:
        digest = news_aggregator.get_digest()["digest"]
        items = news_aggregator.get_news()["items"][:10]
    except Exception:
        digest, items = "News pipeline unavailable.", []
    news_html = "".join(
        f"<li><b>{i['title']}</b><br><small>{i.get('source', '')} · {i.get('section_label', '')}</small></li>"
        for i in items)
    alloc = model["allocations"][0]
    alloc_rows = "".join(
        f"<tr><td>{config.INDICES[i]['name']}</td><td style='text-align:right'>{alloc[i]}%</td></tr>"
        for i in config.INDEX_ORDER)
    return f"""<!doctype html><html><head><meta charset="utf-8">
<title>VittaLens Weekly Digest — {dt.date.today()}</title>
<style>body{{font-family:Segoe UI,sans-serif;max-width:720px;margin:2rem auto;color:#1a1a1a;line-height:1.5}}
h1{{border-bottom:3px solid #D4AF37;padding-bottom:.3rem}}table{{border-collapse:collapse;width:60%}}
td,th{{border:1px solid #ccc;padding:.4rem .6rem}}</style></head><body>
<h1>VittaLens Weekly Digest</h1><p><i>{dt.date.today().strftime('%d %B %Y')}</i></p>
<h2>Market Overview</h2><p>{digest}</p>
<h2>Model Signals</h2>
<p>Projected portfolio CAGR: <b>{s['projected_portfolio_cagr']}%</b> ·
Best index: <b>{config.INDICES[s['best_index']]['name']}</b> ({s['best_index_cagr']}% projected)</p>
<h3>Model allocation — {alloc['month']}</h3><table>{alloc_rows}</table>
<h2>Top News</h2><ul>{news_html or '<li>No items.</li>'}</ul>
<hr><small>Generated by VittaLens · internal use only · not investment advice</small>
</body></html>"""
